/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import DatabaseLayer.DBConnection;
import DatabaseLayer.DBUserConnection;
import Models.Documentation;
import java.awt.Desktop;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;




public class Document extends javax.swing.JInternalFrame {
    Models.Documentation doc;
    String filepath;
    /**
     * Creates new form Document
     */
    public Document() {
        initComponents();
        doc = new Documentation();
        showTableData();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFilePath = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPath = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtPathID = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 132, 909, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("File Location ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, -1, -1));

        btnSelect.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSelect.setText("Select Item");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 178, -1, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 178, -1, -1));

        btnOpen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOpen.setForeground(new java.awt.Color(0, 51, 204));
        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 178, 102, -1));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 178, 120, -1));

        tblPath.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Path Id", "Path"
            }
        ));
        tblPath.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblPath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPathMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPath);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 278, 556, 172));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 229, 111, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Document Table");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 232, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Document");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 13, -1, -1));

        lblID.setText("Path ID");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 97, -1, -1));

        txtPathID.setEditable(false);
        getContentPane().add(txtPathID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String path = txtFilePath.getText();
        
        if ((path.isEmpty())){
            JOptionPane.showMessageDialog(this, "Please Select Correct path");
        }else{
            doc.setDocumentPath(txtFilePath.getText());
           
            DatabaseLayer.DBUserConnection up = new DBUserConnection();
            up.AddDocumentation(doc);
            JOptionPane.showMessageDialog(this, "Path Added");
            
            txtFilePath.setText("");
            
            showTableData();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        JFileChooser fileC = new JFileChooser();
        fileC.showOpenDialog(this);
        
        try{
           
            File file = fileC.getSelectedFile();
            filepath = file.getAbsolutePath();
            filepath = filepath.replace('\\','/');
            txtFilePath.setText(filepath);
            
        }catch(Exception ex){
            Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        filepath = txtFilePath.getText();
        
        try{

            File OpenFile = new File(filepath);
            if (OpenFile.exists()){
                if (Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(OpenFile);
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Not Supported");
                }    
            }else{
                JOptionPane.showMessageDialog(rootPane, "File is not Exit");
            }  
        }catch(Exception ex){
            Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }   
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtFilePath.setText("");
        txtPathID.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblPathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPathMouseClicked
        int row = tblPath.getSelectedRow();
            TableModel model = tblPath.getModel();
            txtPathID.setText(model.getValueAt(row, 0).toString());
            txtFilePath.setText(model.getValueAt(row, 1).toString());
    }//GEN-LAST:event_tblPathMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DBConnection con = new DBConnection();
        
        String sql = "delete from Documentation where DocumentID = ?";
        try {
             PreparedStatement prep = con.getDBConnection().prepareStatement(sql);
             prep.setString(1, txtPathID.getText().toString());
             prep.execute();
             
             JOptionPane.showMessageDialog(null, "Deleted");
             
             txtPathID.setText("");
             txtFilePath.setText("");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
         showTableData();
    }//GEN-LAST:event_btnDeleteActionPerformed
    public void showTableData() {

        try {
            DBConnection con = new DBConnection();
            String sql = "select * from Documentation";
            PreparedStatement prep = con.getDBConnection().prepareStatement(sql);
            prep.executeQuery();

            tblPath.setModel(DbUtils.resultSetToTableModel(prep.executeQuery()));

        } catch (Exception ex) {
            Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JTable tblPath;
    private javax.swing.JTextField txtFilePath;
    private javax.swing.JTextField txtPathID;
    // End of variables declaration//GEN-END:variables
}
