/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Models.AdminUser;
import javax.swing.JOptionPane;
import DatabaseLayer.*;
import java.awt.event.KeyEvent;
import java.awt.EventQueue;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author sange
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    Models.AdminUser User;
    String type;

    public SignUp() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        User = new AdminUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpAdminUser = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        pwdPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        pwdCon = new javax.swing.JPasswordField();
        cmbSecurity = new javax.swing.JComboBox<>();
        txtAnswer = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        rdbAdmin = new javax.swing.JRadioButton();
        rdbUser = new javax.swing.JRadioButton();
        chkShow = new javax.swing.JCheckBox();
        lblName = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblAnswer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Add New User");

        jLabel2.setText("Name");

        jLabel3.setText("User Name");

        jLabel4.setText("Password");

        jLabel5.setText("Security Question");

        jLabel6.setText("Answer");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNameKeyReleased(evt);
            }
        });

        pwdPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdPassKeyPressed(evt);
            }
        });

        jLabel7.setText("Confirm Password");

        pwdCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdConKeyPressed(evt);
            }
        });

        cmbSecurity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your mother's name?", "What are the last four numbers of your mobile no.?", "What is your first school?", "what is your first class teacher's name?", " " }));
        cmbSecurity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSecurityActionPerformed(evt);
            }
        });
        cmbSecurity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbSecurityKeyPressed(evt);
            }
        });

        txtAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAnswerKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAnswerKeyReleased(evt);
            }
        });

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        btnAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddKeyPressed(evt);
            }
        });

        jLabel8.setText("Type");

        grpAdminUser.add(rdbAdmin);
        rdbAdmin.setText("Admin");
        rdbAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbAdminActionPerformed(evt);
            }
        });
        rdbAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rdbAdminKeyPressed(evt);
            }
        });

        grpAdminUser.add(rdbUser);
        rdbUser.setText("User");
        rdbUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbUserActionPerformed(evt);
            }
        });
        rdbUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rdbUserKeyPressed(evt);
            }
        });

        chkShow.setText("Show Password");
        chkShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowActionPerformed(evt);
            }
        });

        lblName.setForeground(new java.awt.Color(204, 0, 0));

        lblUserName.setForeground(new java.awt.Color(204, 0, 0));

        lblAnswer.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtUserName)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pwdCon)
                                    .addComponent(pwdPass)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(chkShow)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdbAdmin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdbUser))
                                    .addComponent(lblAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAnswer)
                                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmbSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 8, Short.MAX_VALUE))
                                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(59, 59, 59))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pwdPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pwdCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkShow)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rdbAdmin)
                    .addComponent(rdbUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        User.setName(txtName.getText().trim());
        User.setUserName(txtUserName.getText().trim());
        String pw = pwdPass.getText();
        String cp = pwdCon.getText();

        if (pw.equals(cp)) {
            User.setPassword(pw);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Check password again");
        }

        User.setSecurityQuestion(cmbSecurity.getSelectedItem().toString());
        User.setAnswer(txtAnswer.getText().trim());
        User.setType(type);
        DatabaseLayer.DBUserConnection up = new DBUserConnection();

        up.AddUser(User);
        JOptionPane.showMessageDialog(rootPane, "New User Added.");
        this.setVisible(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void rdbAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbAdminActionPerformed
        type = "Admin";
    }//GEN-LAST:event_rdbAdminActionPerformed

    private void rdbUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbUserActionPerformed
        type = "User";
    }//GEN-LAST:event_rdbUserActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed

    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtUserName.requestFocus();
        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pwdPass.requestFocus();
        }
    }//GEN-LAST:event_txtUserNameKeyPressed

    private void pwdPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdPassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pwdCon.requestFocus();
        }
    }//GEN-LAST:event_pwdPassKeyPressed

    private void pwdConKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdConKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cmbSecurity.requestFocus();
        }
    }//GEN-LAST:event_pwdConKeyPressed

    private void cmbSecurityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbSecurityKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtAnswer.requestFocus();
        }
    }//GEN-LAST:event_cmbSecurityKeyPressed

    private void txtAnswerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnswerKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            rdbAdmin.requestFocus();
        }
    }//GEN-LAST:event_txtAnswerKeyPressed

    private void rdbAdminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdbAdminKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            rdbUser.requestFocus();
            rdbAdmin.setSelected(false);
        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            rdbAdmin.setSelected(true);
            btnAdd.requestFocus();

        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txtAnswer.requestFocus();

        }

    }//GEN-LAST:event_rdbAdminKeyPressed

    private void rdbUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdbUserKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            rdbUser.setSelected(true);
            btnAdd.requestFocus();

        }
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            rdbAdmin.requestFocus();
            rdbUser.setSelected(false);

        }
    }//GEN-LAST:event_rdbUserKeyPressed

    private void btnAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            rdbUser.requestFocus();

        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            User.setName(txtName.getText().trim());
            User.setUserName(txtUserName.getText().trim());
            String pw = pwdPass.getText();
            String cp = pwdCon.getText();

            if (pw.equals(cp)) {
                User.setPassword(pw);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Check password agin");
            }

            User.setSecurityQuestion(cmbSecurity.getSelectedItem().toString());
            User.setAnswer(txtAnswer.getText().trim());
            User.setType(type);
            DatabaseLayer.DBUserConnection up = new DBUserConnection();

            up.AddUser(User);
            JOptionPane.showMessageDialog(rootPane, "New User Added.");
            this.setVisible(false);

        }

    }//GEN-LAST:event_btnAddKeyPressed

    private void chkShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowActionPerformed
        if (chkShow.isSelected()) {
            pwdPass.setEchoChar((char) 0);
            pwdCon.setEchoChar((char) 0);
        } else {
            pwdPass.setEchoChar('*');
            pwdCon.setEchoChar('*');
        }
    }//GEN-LAST:event_chkShowActionPerformed

    private void cmbSecurityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSecurityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSecurityActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        String namePattern = "^[a-zA-Z\\s]{0,30}$";
        Pattern patt = Pattern.compile(namePattern);
        Matcher match = patt.matcher(txtName.getText());
        if (!match.matches()) {
            lblName.setText("Naming is incorrect");
        } else {
            lblName.setText(null);
        }
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyReleased
        // TODO add your handling code here:
        String namePattern = "^[a-zA-Z0-9]{0,30}$";
        Pattern patt = Pattern.compile(namePattern);
        Matcher match = patt.matcher(txtUserName.getText());
        if (!match.matches()) {
            lblUserName.setText("Incorrect User name format");
        } else {
            lblUserName.setText(null);
        }
    }//GEN-LAST:event_txtUserNameKeyReleased

    private void txtAnswerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnswerKeyReleased
        // TODO add your handling code here:
        String namePattern = "^[a-zA-Z0-9\\s]{0,30}$";
        Pattern patt = Pattern.compile(namePattern);
        Matcher match = patt.matcher(txtAnswer.getText());
        if (!match.matches()) {
            lblAnswer.setText("Incorrect answer format?");
        } else {
            lblAnswer.setText(null);
        }
    }//GEN-LAST:event_txtAnswerKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JCheckBox chkShow;
    private javax.swing.JComboBox<String> cmbSecurity;
    private javax.swing.ButtonGroup grpAdminUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField pwdCon;
    private javax.swing.JPasswordField pwdPass;
    private javax.swing.JRadioButton rdbAdmin;
    private javax.swing.JRadioButton rdbUser;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
