/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import DatabaseLayer.DBConnection;
import DatabaseLayer.DBUserConnection;
import Models.TransactionAdd;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sange
 */
public class Transaction extends javax.swing.JInternalFrame {

    Models.TransactionAdd trns;
    /**
     * Creates new form Class
     */
    DBUserConnection meth = new DBUserConnection();
    public Transaction() {
        trns = new TransactionAdd();
        initComponents();
        showTableData();
        showTableDataStu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTransaction = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblStudent = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSearchByStu = new javax.swing.JTextField();
        cmbsearByStu = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtTrnsId = new javax.swing.JTextField();
        txtStuId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtStuName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        cmbGrade = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtReciptId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnPrint = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaRecipt = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cmbMonth = new javax.swing.JComboBox<>();
        txtSubject = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableTransaction.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jTableTransaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTransactionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTransaction);

        jTblStudent.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jTblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblStudentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTblStudent);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Transaction Table :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Student Table :");

        jLabel13.setText("Search Student");

        cmbsearByStu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select Type - ", "Student_ID", "Name", "Contact", "E-Mail", "Grade", "Class", "Guardian" }));
        cmbsearByStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsearByStuActionPerformed(evt);
            }
        });

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 522, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchByStu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbsearByStu, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSearchByStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbsearByStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 1160, 910));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Transaction Id :");

        txtTrnsId.setEditable(false);

        txtStuId.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Student Id :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Student Name :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Fee Amount : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Month : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Description : ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Student E-mail : ");

        cmbGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Grade-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "A/L" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Student Grade : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Student Subject : ");

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setText(" CLEAR");
        btnClear.setPreferredSize(new java.awt.Dimension(71, 23));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Recipt Id :");

        txtReciptId.setEditable(false);

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrint.setText(" Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        txtAreaRecipt.setColumns(20);
        txtAreaRecipt.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        txtAreaRecipt.setRows(5);
        jScrollPane3.setViewportView(txtAreaRecipt);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Receipt  :");

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setText(" ADD");
        btnAdd.setPreferredSize(new java.awt.Dimension(71, 23));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel18.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 255));
        jLabel18.setText("Transaction");

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select Month -", "January\t", "February\t", "March\t", "April\t", "May\t", "June\t", "July\t", "August\t", "September\t", "October\t", "November\t", "December\t" }));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Generate Recipt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtReciptId)
                                    .addComponent(txtStuName)
                                    .addComponent(txtAmount)
                                    .addComponent(txtDescription)
                                    .addComponent(txtStuId)
                                    .addComponent(txtTrnsId)
                                    .addComponent(cmbGrade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmail)
                                    .addComponent(cmbMonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSubject))
                                .addGap(25, 25, 25)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(50, 50, 50)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTrnsId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStuId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtReciptId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtTrnsId.setText("");
        txtStuId.setText("");
        txtStuName.setText("");
        txtAmount.setText("");
        cmbMonth.setSelectedIndex(0);
        txtDescription.setText("");
        cmbGrade.setSelectedIndex(0);
        txtSubject.setText("");
        txtEmail.setText("");
        cmbGrade.setSelectedIndex(0);
        
        txtAreaRecipt.setText("");
        txtReciptId.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String StuId = txtStuId.getText();
        String Name = txtStuName.getText();
        String Amount = txtAmount.getText();
        int Date =  cmbMonth.getSelectedIndex();
        String Depcri = txtDescription.getText();
        String Email = txtEmail.getText();
        String ReciptId = txtReciptId.getText();
        int grade = cmbGrade.getSelectedIndex();
        String Subject = txtSubject.getText();
            
        if ((grade == 0 )|| (Subject.isEmpty()) || (Name.isEmpty()) || (ReciptId.isEmpty()) || (Amount.isEmpty()) || (Date == 0) || (Depcri.isEmpty()) || (Email.isEmpty()) || (StuId.isEmpty())){
            JOptionPane.showMessageDialog(this, "Please Insert Correct Value or fill all data");
        }
        else{
            trns.setStuId(txtStuId.getText());
            trns.setStudentName(txtStuName.getText());
            trns.setAmount(txtAmount.getText());
            trns.setPaidMonth(cmbMonth.getSelectedItem().toString());
            trns.setDescription(txtDescription.getText());
            trns.setEmail(txtEmail.getText());
            trns.setGrade(cmbGrade.getSelectedItem().toString());
            trns.setStudentSubject(txtSubject.getText());
            trns.setReciptId(txtReciptId.getText());
            DatabaseLayer.DBUserConnection up = new DBUserConnection();
            up.AddTransaction(trns);
                
            txtTrnsId.setText("");
            txtStuId.setText("");
            txtStuName.setText("");
            txtAmount.setText("");
            cmbMonth.setSelectedIndex(0);
            txtDescription.setText("");
            txtEmail.setText("");
            cmbGrade.setSelectedIndex(0);
            txtSubject.setText("");
            txtReciptId.setText("");
            
            JOptionPane.showMessageDialog(this, "Transaction Added Successfully  :-) ");
            showTableData();
            showTableDataStu();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jTblStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblStudentMouseClicked
        int row = jTblStudent.getSelectedRow();
        TableModel model = jTblStudent.getModel();
        txtTrnsId.setText("");
        txtStuId.setText(model.getValueAt(row, 0).toString());
        txtStuName.setText(model.getValueAt(row, 1).toString());
        txtAmount.setText("");
        cmbMonth.setSelectedIndex(0);;
        txtDescription.setText("");
        txtEmail.setText(model.getValueAt(row, 3).toString());
        String grade = model.getValueAt(row, 5).toString();
            switch(grade){
                case "1":
                    cmbGrade.setSelectedIndex(1);
                    break;
                case "2":
                    cmbGrade.setSelectedIndex(2);
                    break;
                case "3":
                    cmbGrade.setSelectedIndex(3);
                    break;
                case "4":
                    cmbGrade.setSelectedIndex(4);
                    break;
                case "5":
                    cmbGrade.setSelectedIndex(5);
                    break;
                case "6":
                    cmbGrade.setSelectedIndex(6);
                    break;
                case "7":
                    cmbGrade.setSelectedIndex(7);
                    break;
                case "8":
                    cmbGrade.setSelectedIndex(8);
                    break;
                case "9":
                    cmbGrade.setSelectedIndex(9);
                    break;
                case "10":
                    cmbGrade.setSelectedIndex(10);
                    break;
                case "11":
                    cmbGrade.setSelectedIndex(11);
                    break;
                case "A/L":
                    cmbGrade.setSelectedIndex(12);
                    break;
            }
        
        txtSubject.setText(model.getValueAt(row, 6).toString());
            
    }//GEN-LAST:event_jTblStudentMouseClicked

    private void jTableTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTransactionMouseClicked
        int row = jTableTransaction.getSelectedRow();
        TableModel model = jTableTransaction.getModel();
        txtTrnsId.setText(model.getValueAt(row, 0).toString());
        txtStuId.setText(model.getValueAt(row, 1).toString());
        txtStuName.setText(model.getValueAt(row, 2).toString());
        txtReciptId.setText(model.getValueAt(row, 3).toString());
        txtAmount.setText(model.getValueAt(row, 4).toString());
        String Month = model.getValueAt(row, 5).toString();
            switch(Month){
                case "January":
                    cmbMonth.setSelectedIndex(1);
                    break;
                case "February":
                    cmbMonth.setSelectedIndex(2);
                    break;
                case "March":
                    cmbMonth.setSelectedIndex(3);
                    break;
                case "April":
                    cmbMonth.setSelectedIndex(4);
                    break;
                case "May":
                    cmbMonth.setSelectedIndex(5);
                    break;
                case "June":
                    cmbMonth.setSelectedIndex(6);
                    break;
                case "July":
                    cmbMonth.setSelectedIndex(7);
                    break;
                case "August":
                    cmbMonth.setSelectedIndex(8);
                    break;
                case "September":
                    cmbMonth.setSelectedIndex(9);
                    break;
                case "October":
                    cmbMonth.setSelectedIndex(10);
                    break;
                case "November":
                    cmbMonth.setSelectedIndex(11);
                    break;
                case "December":
                    cmbMonth.setSelectedIndex(12);
                    break;
            }
        txtDescription.setText(model.getValueAt(row, 6).toString());
        String grade = model.getValueAt(row, 7).toString();
            switch(grade){
                case "1":
                    cmbGrade.setSelectedIndex(1);
                    break;
                case "2":
                    cmbGrade.setSelectedIndex(2);
                    break;
                case "3":
                    cmbGrade.setSelectedIndex(3);
                    break;
                case "4":
                    cmbGrade.setSelectedIndex(4);
                    break;
                case "5":
                    cmbGrade.setSelectedIndex(5);
                    break;
                case "6":
                    cmbGrade.setSelectedIndex(6);
                    break;
                case "7":
                    cmbGrade.setSelectedIndex(7);
                    break;
                case "8":
                    cmbGrade.setSelectedIndex(8);
                    break;
                case "9":
                    cmbGrade.setSelectedIndex(9);
                    break;
                case "10":
                    cmbGrade.setSelectedIndex(10);
                    break;
                case "11":
                    cmbGrade.setSelectedIndex(11);
                    break;
                case "A/L":
                    cmbGrade.setSelectedIndex(12);
                    break;
            }
        txtSubject.setText(model.getValueAt(row, 8).toString());
           
        txtEmail.setText(model.getValueAt(row, 9).toString());
    }//GEN-LAST:event_jTableTransactionMouseClicked

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try{
            txtAreaRecipt.print();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String stname =  txtStuName.getText();
        String Subject = txtSubject.getText();
        int grade = cmbGrade.getSelectedIndex();
        
        String Amount = txtAmount.getText();
        String DaTE =  cmbMonth.getSelectedItem().toString() ;
        String dES =  txtDescription.getText();
        String EMAIL = txtEmail.getText() ;
        if ((stname.isEmpty() )|| (Subject.isEmpty()) || (grade == 0) || (Amount.isEmpty()) || (DaTE.isEmpty()) || (dES.isEmpty()) || (EMAIL.isEmpty())){
                    JOptionPane.showMessageDialog(this, "First Fill the form to generate bill");
        }
        else{
            String id = "CELS_00000";
            int row = jTableTransaction.getRowCount();
            int iscount = row + 1;
            String out = id + Integer.toString(iscount);
            txtAreaRecipt.setText("***********************************************\n");
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "*      Cambridge English Language School      *\n");
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "*                 561\\64,                     *\n");
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "*              1st Pola Road,                 *\n");
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "*              New Bus Stand,                 *\n");
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "*               Anuradhapura.                 *\n"); 
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "***********************************************\n");
        
            Date obj = new Date();
        
            String date = obj.toString();
            String dte[] = date.split(" ");
            txtAreaRecipt.setText(txtAreaRecipt.getText() +"-----------------------------------------------\n");
            txtAreaRecipt.setText(txtAreaRecipt.getText() +"Date \t\t\t  Time             " + "\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() + dte[0]+" "+dte[1]+" "+dte[2]+" "+dte[5] +"\t\t  "+ dte[3]+ "\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() +"Recipt Id       : " + out +"\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() +"-----------------------------------------------\n\n");
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "Student ID      : " + txtStuId.getText() + "\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "Student Name    : " + txtStuName.getText() + "\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "Student Grade   : Grade " + cmbGrade.getSelectedItem().toString() + "\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "Subjects        : " + txtSubject.getText() + "\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "Fees Amount     : " + txtAmount.getText() + "\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "Paid Month      : " + cmbMonth.getSelectedItem().toString() + "\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "Description     : " + txtDescription.getText() + "\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "Student E-Mail  : " + txtEmail.getText() + "\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() +"-----------------------------------------------\n");
            txtAreaRecipt.setText(txtAreaRecipt.getText() +"Class fee Amount : RS " +txtAmount.getText()+"\n");
            txtAreaRecipt.setText(txtAreaRecipt.getText() +"-----------------------------------------------\n");
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "                                 ___________" + "\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "                                  Signature" + "\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"+"\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "@@@  < THANK YOU, LET'S LEARN EVERYTHING >  @@@"+"\n" );
            txtAreaRecipt.setText(txtAreaRecipt.getText() + "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"+"\n" );
        
            txtReciptId.setText(out);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmbsearByStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsearByStuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbsearByStuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DBConnection con = new DBConnection();
        String by = cmbsearByStu.getSelectedItem().toString();
        if(by=="Student_ID"){
        try
        {
            String search = txtSearchByStu.getText();
            String sql = "select * from Student where (Student_ID='"+search+"')";
            PreparedStatement prep = con.getDBConnection().prepareStatement(sql);
            ResultSet rs = prep.executeQuery();  
            jTblStudent.setModel(DbUtils.resultSetToTableModel(rs));            
            
        }catch(Exception ex)
        {
                Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Enter value to search");        
        }
        
        }
        else if(by=="Name")
        {
        try    
         {
            String search = txtSearchByStu.getText();
            String sql = "select * from Student where (Name='"+search+"')";
            PreparedStatement prep = con.getDBConnection().prepareStatement(sql);
            ResultSet rs = prep.executeQuery();  
            jTblStudent.setModel(DbUtils.resultSetToTableModel(rs));            
            
        }catch(Exception ex)
        {
                Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Enter value to search");        
        }       
        
        }
        else if(by=="Contact")
        {
        try    
         {
            String search = txtSearchByStu.getText();
            String sql = "select * from Student where (Contact='"+search+"')";
            PreparedStatement prep = con.getDBConnection().prepareStatement(sql);
            ResultSet rs = prep.executeQuery();  
            jTblStudent.setModel(DbUtils.resultSetToTableModel(rs));            
            
        }catch(Exception ex)
        {
                Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Enter value to search");        
        } 
        
        
        }
        else if(by=="Email")
        {
        try    
         {
            String search = txtSearchByStu.getText();
            String sql = "select * from Student where (Email='"+search+"')";
            PreparedStatement prep = con.getDBConnection().prepareStatement(sql);
            ResultSet rs = prep.executeQuery();  
            jTblStudent.setModel(DbUtils.resultSetToTableModel(rs));            
            
        }catch(Exception ex)
        {
                Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Enter value to search");        
        } 
        }
        else if(by=="Grade")
        {
        try    
         {
            String search = txtSearchByStu.getText();
            String sql = "select * from Student where (Grade='"+search+"')";
            PreparedStatement prep = con.getDBConnection().prepareStatement(sql);
            ResultSet rs = prep.executeQuery();  
            jTblStudent.setModel(DbUtils.resultSetToTableModel(rs));            
            
        }catch(Exception ex)
        {
                Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Enter value to search");        
        } 
        }
        
        else if(by=="Class")
        {
        try    
         {
            String search = txtSearchByStu.getText();
            String sql = "select * from Student where (Class='"+search+"')";
            PreparedStatement prep = con.getDBConnection().prepareStatement(sql);
            ResultSet rs = prep.executeQuery();  
            jTblStudent.setModel(DbUtils.resultSetToTableModel(rs));            
            
        }catch(Exception ex)
        {
                Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Enter value to search");        
        } 
        }
        else if(by=="Guardian")
        {
        try    
         {
            String search = txtSearchByStu.getText();
            String sql = "select * from Student where (Guardian='"+search+"')";
            PreparedStatement prep = con.getDBConnection().prepareStatement(sql);
            ResultSet rs = prep.executeQuery();  
            jTblStudent.setModel(DbUtils.resultSetToTableModel(rs));            
            
        }catch(Exception ex)
        {
                Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Enter value to search");        
        } 
        }
        
        txtSearchByStu.setText("");
        cmbsearByStu.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void showTableData() {

        try {
            DBConnection con = new DBConnection();
            String sql = "SELECT * from Transactions";
            PreparedStatement prep = con.getDBConnection().prepareStatement(sql);
            prep.executeQuery();

            jTableTransaction.setModel(DbUtils.resultSetToTableModel(prep.executeQuery()));

        } catch (Exception ex) {
            Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    public void showTableDataStu(){
       DBConnection con = new DBConnection();
      try
      {   //Student_ID,Name,Contact,Email,Occupation,Grade,Class
          String sql = "select Student_ID,Name,Contact,Email,Occupation,Grade,Class from Student WHERE Occupation='Student'";
          PreparedStatement prep = con.getDBConnection().prepareStatement(sql);
          ResultSet rs = prep.executeQuery();  
          jTblStudent.setModel(DbUtils.resultSetToTableModel(rs));
          
      }
      catch(SQLException ex)
      {
            Logger.getLogger(DBConnection.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());          
      }   
    
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox<String> cmbGrade;
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JComboBox<String> cmbsearByStu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableTransaction;
    private javax.swing.JTable jTblStudent;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextArea txtAreaRecipt;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtReciptId;
    private javax.swing.JTextField txtSearchByStu;
    private javax.swing.JTextField txtStuId;
    private javax.swing.JTextField txtStuName;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtTrnsId;
    // End of variables declaration//GEN-END:variables
}
